; ===========================================================================
;  info.asm -- таблицы состояний (states) и параметров объектов (mobjinfo),
;              как info.c в DOOM. Номера состояний назначаются автоматически.
; ===========================================================================

%define FF_FULLBRIGHT 0x8000

; --------------------------- спрайты ---------------------------------------
%define SPR_PLAY    0
%define SPR_POSS    1
%define SPR_SPOS    2
%define SPR_TROO    3
%define SPR_SARG    4
%define SPR_HEAD    5
%define SPR_BOSS    6
%define SPR_SKUL    7
%define SPR_BAL1    8
%define SPR_BAL7    9
%define SPR_MISL    10
%define SPR_PLSS    11
%define SPR_BFS1    12
%define SPR_PUFF    13
%define SPR_BLUD    14
%define SPR_TFOG    15
%define SPR_BAR1    16
%define SPR_BEXP    17
%define SPR_COLU    18
%define SPR_BON1    20
%define SPR_BON2    21
%define SPR_STIM    22
%define SPR_MEDI    23
%define SPR_ARM1    24
%define SPR_ARM2    25
%define SPR_CLIP    26
%define SPR_AMMO    27
%define SPR_SHEL    28
%define SPR_SBOX    29
%define SPR_ROCK    30
%define SPR_BROK    31
%define SPR_CELL    32
%define SPR_CELP    33
%define SPR_BPAK    34
%define SPR_BKEY    35
%define SPR_YKEY    36
%define SPR_RKEY    37
%define SPR_SHOT    38
%define SPR_MGUN    39
%define SPR_LAUN    40
%define SPR_PLAS    41
%define SPR_BFUG    42
%define SPR_CSAW    43
%define SPR_SOUL    44
%define SPR_PINV    45
%define SPR_PSTR    46
%define SPR_PINS    47
%define SPR_SUIT    48
%define SPR_PMAP    49
%define SPR_PVIS    50
; графика оружия в руках
%define SPR_PUNG    51
%define SPR_PISG    52
%define SPR_SHTG    53
%define SPR_CHGG    54
%define SPR_MISG    55
%define SPR_PLSG    56
%define SPR_BFGG    57
%define SPR_SAWG    58
%define SPR_FLSH    59
%define NUMSPRITES  60

; --------------------------- действия --------------------------------------
%define A_NULL          0
%define A_Look          1
%define A_Chase         2
%define A_FaceTarget    3
%define A_PosAttack     4
%define A_SPosAttack    5
%define A_TroopAttack   6
%define A_SargAttack    7
%define A_HeadAttack    8
%define A_BruisAttack   9
%define A_SkullAttack   10
%define A_Scream        11
%define A_XScream       12
%define A_Pain          13
%define A_Fall          14
%define A_Explode       15
%define A_BossDeath     16
%define A_WeaponReady   17
%define A_Lower         18
%define A_Raise         19
%define A_Punch         20
%define A_ReFire        21
%define A_FirePistol    22
%define A_FireShotgun   23
%define A_FireCGun      24
%define A_FireMissile   25
%define A_FirePlasma    26
%define A_FireBFG       27
%define A_BFGSpray      28
%define A_Light0        29
%define A_Light1        30
%define A_Light2        31
%define A_GunFlash      32
%define A_CheckReload   33
%define A_Saw           34
%define A_PlayerScream  35
%define A_BarrelDie     36
%define NUMACTIONS      37

; --------------------------- макросы состояний ------------------------------
%assign NST 0

; STDEF имя, спрайт, кадр, тики, действие, следующее
%macro STDEF 6
    %assign %1 NST
    %assign NST NST+1
    dd %2, %3, %4, %5, %6, 0, 0, 0
%endmacro

; STSEQ имя, спрайт, кадр, тики, действие  -- следующее = текущее+1
%macro STSEQ 5
    %assign %1 NST
    %assign NST NST+1
    dd %2, %3, %4, %5, %1+1, 0, 0, 0
%endmacro

    align 8
states:
    STDEF S_NULL,      0,        0, -1, A_NULL, S_NULL

; ------------------------------ игрок --------------------------------------
    STDEF S_PLAY,      SPR_PLAY, 0, -1, A_NULL, S_PLAY
    STSEQ S_PLAY_RUN1, SPR_PLAY, 0,  4, A_NULL
    STSEQ S_PLAY_RUN2, SPR_PLAY, 1,  4, A_NULL
    STSEQ S_PLAY_RUN3, SPR_PLAY, 2,  4, A_NULL
    STDEF S_PLAY_RUN4, SPR_PLAY, 3,  4, A_NULL, S_PLAY_RUN1
    STDEF S_PLAY_ATK1, SPR_PLAY, 4, 12, A_NULL, S_PLAY
    STSEQ S_PLAY_PAIN, SPR_PLAY, 6,  4, A_NULL
    STDEF S_PLAY_PAIN2,SPR_PLAY, 6,  4, A_Pain, S_PLAY
    STSEQ S_PLAY_DIE1, SPR_PLAY, 7, 10, A_NULL
    STSEQ S_PLAY_DIE2, SPR_PLAY, 8, 10, A_PlayerScream
    STSEQ S_PLAY_DIE3, SPR_PLAY, 9, 10, A_Fall
    STSEQ S_PLAY_DIE4, SPR_PLAY, 10,10, A_NULL
    STSEQ S_PLAY_DIE5, SPR_PLAY, 11,10, A_NULL
    STDEF S_PLAY_DIE6, SPR_PLAY, 12,-1, A_NULL, S_PLAY_DIE6

; ------------------------------ зомби --------------------------------------
    STSEQ S_POSS_STND, SPR_POSS, 0, 10, A_Look
    STDEF S_POSS_STND2,SPR_POSS, 1, 10, A_Look, S_POSS_STND
    STSEQ S_POSS_RUN1, SPR_POSS, 0,  4, A_Chase
    STSEQ S_POSS_RUN2, SPR_POSS, 0,  4, A_Chase
    STSEQ S_POSS_RUN3, SPR_POSS, 1,  4, A_Chase
    STSEQ S_POSS_RUN4, SPR_POSS, 1,  4, A_Chase
    STSEQ S_POSS_RUN5, SPR_POSS, 2,  4, A_Chase
    STSEQ S_POSS_RUN6, SPR_POSS, 2,  4, A_Chase
    STSEQ S_POSS_RUN7, SPR_POSS, 3,  4, A_Chase
    STDEF S_POSS_RUN8, SPR_POSS, 3,  4, A_Chase, S_POSS_RUN1
    STSEQ S_POSS_ATK1, SPR_POSS, 4, 10, A_FaceTarget
    STSEQ S_POSS_ATK2, SPR_POSS, 5,  8, A_PosAttack
    STDEF S_POSS_ATK3, SPR_POSS, 4,  8, A_NULL, S_POSS_RUN1
    STSEQ S_POSS_PAIN, SPR_POSS, 6,  3, A_NULL
    STDEF S_POSS_PAIN2,SPR_POSS, 6,  3, A_Pain, S_POSS_RUN1
    STSEQ S_POSS_DIE1, SPR_POSS, 7,  5, A_NULL
    STSEQ S_POSS_DIE2, SPR_POSS, 8,  5, A_Scream
    STSEQ S_POSS_DIE3, SPR_POSS, 9,  5, A_Fall
    STSEQ S_POSS_DIE4, SPR_POSS, 10, 5, A_NULL
    STDEF S_POSS_DIE5, SPR_POSS, 11,-1, A_NULL, S_POSS_DIE5

; --------------------------- сержант с дробовиком --------------------------
    STSEQ S_SPOS_STND, SPR_SPOS, 0, 10, A_Look
    STDEF S_SPOS_STND2,SPR_SPOS, 1, 10, A_Look, S_SPOS_STND
    STSEQ S_SPOS_RUN1, SPR_SPOS, 0,  3, A_Chase
    STSEQ S_SPOS_RUN2, SPR_SPOS, 0,  3, A_Chase
    STSEQ S_SPOS_RUN3, SPR_SPOS, 1,  3, A_Chase
    STSEQ S_SPOS_RUN4, SPR_SPOS, 1,  3, A_Chase
    STSEQ S_SPOS_RUN5, SPR_SPOS, 2,  3, A_Chase
    STSEQ S_SPOS_RUN6, SPR_SPOS, 2,  3, A_Chase
    STSEQ S_SPOS_RUN7, SPR_SPOS, 3,  3, A_Chase
    STDEF S_SPOS_RUN8, SPR_SPOS, 3,  3, A_Chase, S_SPOS_RUN1
    STSEQ S_SPOS_ATK1, SPR_SPOS, 4, 10, A_FaceTarget
    STSEQ S_SPOS_ATK2, SPR_SPOS, 5|FF_FULLBRIGHT, 10, A_SPosAttack
    STDEF S_SPOS_ATK3, SPR_SPOS, 4, 10, A_NULL, S_SPOS_RUN1
    STSEQ S_SPOS_PAIN, SPR_SPOS, 6,  3, A_NULL
    STDEF S_SPOS_PAIN2,SPR_SPOS, 6,  3, A_Pain, S_SPOS_RUN1
    STSEQ S_SPOS_DIE1, SPR_SPOS, 7,  5, A_NULL
    STSEQ S_SPOS_DIE2, SPR_SPOS, 8,  5, A_Scream
    STSEQ S_SPOS_DIE3, SPR_SPOS, 9,  5, A_Fall
    STSEQ S_SPOS_DIE4, SPR_SPOS, 10, 5, A_NULL
    STDEF S_SPOS_DIE5, SPR_SPOS, 11,-1, A_NULL, S_SPOS_DIE5

; ------------------------------ имп ----------------------------------------
    STSEQ S_TROO_STND, SPR_TROO, 0, 10, A_Look
    STDEF S_TROO_STND2,SPR_TROO, 1, 10, A_Look, S_TROO_STND
    STSEQ S_TROO_RUN1, SPR_TROO, 0,  3, A_Chase
    STSEQ S_TROO_RUN2, SPR_TROO, 0,  3, A_Chase
    STSEQ S_TROO_RUN3, SPR_TROO, 1,  3, A_Chase
    STSEQ S_TROO_RUN4, SPR_TROO, 1,  3, A_Chase
    STSEQ S_TROO_RUN5, SPR_TROO, 2,  3, A_Chase
    STSEQ S_TROO_RUN6, SPR_TROO, 2,  3, A_Chase
    STSEQ S_TROO_RUN7, SPR_TROO, 3,  3, A_Chase
    STDEF S_TROO_RUN8, SPR_TROO, 3,  3, A_Chase, S_TROO_RUN1
    STSEQ S_TROO_ATK1, SPR_TROO, 4,  8, A_FaceTarget
    STSEQ S_TROO_ATK2, SPR_TROO, 5,  8, A_FaceTarget
    STDEF S_TROO_ATK3, SPR_TROO, 6,  6, A_TroopAttack, S_TROO_RUN1
    STSEQ S_TROO_PAIN, SPR_TROO, 7,  2, A_NULL
    STDEF S_TROO_PAIN2,SPR_TROO, 7,  2, A_Pain, S_TROO_RUN1
    STSEQ S_TROO_DIE1, SPR_TROO, 8,  8, A_NULL
    STSEQ S_TROO_DIE2, SPR_TROO, 9,  8, A_Scream
    STSEQ S_TROO_DIE3, SPR_TROO, 10, 6, A_Fall
    STSEQ S_TROO_DIE4, SPR_TROO, 11, 6, A_NULL
    STDEF S_TROO_DIE5, SPR_TROO, 12,-1, A_NULL, S_TROO_DIE5

; ------------------------------ демон --------------------------------------
    STSEQ S_SARG_STND, SPR_SARG, 0, 10, A_Look
    STDEF S_SARG_STND2,SPR_SARG, 1, 10, A_Look, S_SARG_STND
    STSEQ S_SARG_RUN1, SPR_SARG, 0,  2, A_Chase
    STSEQ S_SARG_RUN2, SPR_SARG, 0,  2, A_Chase
    STSEQ S_SARG_RUN3, SPR_SARG, 1,  2, A_Chase
    STSEQ S_SARG_RUN4, SPR_SARG, 1,  2, A_Chase
    STSEQ S_SARG_RUN5, SPR_SARG, 2,  2, A_Chase
    STSEQ S_SARG_RUN6, SPR_SARG, 2,  2, A_Chase
    STSEQ S_SARG_RUN7, SPR_SARG, 3,  2, A_Chase
    STDEF S_SARG_RUN8, SPR_SARG, 3,  2, A_Chase, S_SARG_RUN1
    STSEQ S_SARG_ATK1, SPR_SARG, 4,  8, A_FaceTarget
    STSEQ S_SARG_ATK2, SPR_SARG, 5,  8, A_FaceTarget
    STDEF S_SARG_ATK3, SPR_SARG, 6,  8, A_SargAttack, S_SARG_RUN1
    STSEQ S_SARG_PAIN, SPR_SARG, 7,  2, A_NULL
    STDEF S_SARG_PAIN2,SPR_SARG, 7,  2, A_Pain, S_SARG_RUN1
    STSEQ S_SARG_DIE1, SPR_SARG, 8,  8, A_NULL
    STSEQ S_SARG_DIE2, SPR_SARG, 9,  8, A_Scream
    STSEQ S_SARG_DIE3, SPR_SARG, 10, 4, A_Fall
    STSEQ S_SARG_DIE4, SPR_SARG, 11, 4, A_NULL
    STDEF S_SARG_DIE5, SPR_SARG, 12,-1, A_NULL, S_SARG_DIE5

; ------------------------------ какодемон ----------------------------------
    STDEF S_HEAD_STND, SPR_HEAD, 0, 10, A_Look, S_HEAD_STND
    STSEQ S_HEAD_RUN1, SPR_HEAD, 0,  3, A_Chase
    STSEQ S_HEAD_RUN2, SPR_HEAD, 0,  3, A_Chase
    STDEF S_HEAD_RUN3, SPR_HEAD, 1,  3, A_Chase, S_HEAD_RUN1
    STSEQ S_HEAD_ATK1, SPR_HEAD, 1,  5, A_FaceTarget
    STSEQ S_HEAD_ATK2, SPR_HEAD, 2,  5, A_FaceTarget
    STDEF S_HEAD_ATK3, SPR_HEAD, 3|FF_FULLBRIGHT, 5, A_HeadAttack, S_HEAD_RUN1
    STSEQ S_HEAD_PAIN, SPR_HEAD, 4,  3, A_NULL
    STDEF S_HEAD_PAIN2,SPR_HEAD, 4,  3, A_Pain, S_HEAD_RUN1
    STSEQ S_HEAD_DIE1, SPR_HEAD, 5,  8, A_NULL
    STSEQ S_HEAD_DIE2, SPR_HEAD, 6,  8, A_Scream
    STSEQ S_HEAD_DIE3, SPR_HEAD, 7,  8, A_Fall
    STSEQ S_HEAD_DIE4, SPR_HEAD, 8,  8, A_NULL
    STDEF S_HEAD_DIE5, SPR_HEAD, 9, -1, A_NULL, S_HEAD_DIE5

; ------------------------------ барон --------------------------------------
    STSEQ S_BOSS_STND, SPR_BOSS, 0, 10, A_Look
    STDEF S_BOSS_STND2,SPR_BOSS, 1, 10, A_Look, S_BOSS_STND
    STSEQ S_BOSS_RUN1, SPR_BOSS, 0,  3, A_Chase
    STSEQ S_BOSS_RUN2, SPR_BOSS, 0,  3, A_Chase
    STSEQ S_BOSS_RUN3, SPR_BOSS, 1,  3, A_Chase
    STSEQ S_BOSS_RUN4, SPR_BOSS, 1,  3, A_Chase
    STSEQ S_BOSS_RUN5, SPR_BOSS, 2,  3, A_Chase
    STSEQ S_BOSS_RUN6, SPR_BOSS, 2,  3, A_Chase
    STSEQ S_BOSS_RUN7, SPR_BOSS, 3,  3, A_Chase
    STDEF S_BOSS_RUN8, SPR_BOSS, 3,  3, A_Chase, S_BOSS_RUN1
    STSEQ S_BOSS_ATK1, SPR_BOSS, 4,  8, A_FaceTarget
    STSEQ S_BOSS_ATK2, SPR_BOSS, 5,  8, A_FaceTarget
    STDEF S_BOSS_ATK3, SPR_BOSS, 6,  8, A_BruisAttack, S_BOSS_RUN1
    STDEF S_BOSS_PAIN, SPR_BOSS, 7,  2, A_Pain, S_BOSS_RUN1
    STSEQ S_BOSS_DIE1, SPR_BOSS, 8,  8, A_NULL
    STSEQ S_BOSS_DIE2, SPR_BOSS, 9,  8, A_Scream
    STSEQ S_BOSS_DIE3, SPR_BOSS, 10, 8, A_Fall
    STSEQ S_BOSS_DIE4, SPR_BOSS, 11, 8, A_NULL
    STDEF S_BOSS_DIE5, SPR_BOSS, 12,-1, A_BossDeath, S_BOSS_DIE5

; --------------------------- потерянная душа --------------------------------
    STSEQ S_SKULL_STND,SPR_SKUL, 0|FF_FULLBRIGHT, 10, A_Look
    STDEF S_SKULL_STND2,SPR_SKUL,1|FF_FULLBRIGHT, 10, A_Look, S_SKULL_STND
    STSEQ S_SKULL_RUN1,SPR_SKUL, 0|FF_FULLBRIGHT, 6, A_Chase
    STDEF S_SKULL_RUN2,SPR_SKUL, 1|FF_FULLBRIGHT, 6, A_Chase, S_SKULL_RUN1
    STSEQ S_SKULL_ATK1,SPR_SKUL, 2|FF_FULLBRIGHT, 10, A_FaceTarget
    STSEQ S_SKULL_ATK2,SPR_SKUL, 3|FF_FULLBRIGHT, 4, A_SkullAttack
    STSEQ S_SKULL_ATK3,SPR_SKUL, 2|FF_FULLBRIGHT, 4, A_NULL
    STDEF S_SKULL_ATK4,SPR_SKUL, 3|FF_FULLBRIGHT, 4, A_NULL, S_SKULL_ATK3
    STSEQ S_SKULL_PAIN,SPR_SKUL, 4|FF_FULLBRIGHT, 3, A_NULL
    STDEF S_SKULL_PAIN2,SPR_SKUL,4|FF_FULLBRIGHT, 3, A_Pain, S_SKULL_RUN1
    STSEQ S_SKULL_DIE1,SPR_SKUL, 5|FF_FULLBRIGHT, 6, A_NULL
    STSEQ S_SKULL_DIE2,SPR_SKUL, 6|FF_FULLBRIGHT, 6, A_Scream
    STSEQ S_SKULL_DIE3,SPR_SKUL, 7|FF_FULLBRIGHT, 6, A_Fall
    STDEF S_SKULL_DIE4,SPR_SKUL, 8, 6, A_NULL, S_NULL

; ------------------------------ снаряды ------------------------------------
    STSEQ S_TBALL1,    SPR_BAL1, 0|FF_FULLBRIGHT, 4, A_NULL
    STDEF S_TBALL2,    SPR_BAL1, 1|FF_FULLBRIGHT, 4, A_NULL, S_TBALL1
    STSEQ S_TBALLX1,   SPR_BAL1, 2|FF_FULLBRIGHT, 6, A_NULL
    STSEQ S_TBALLX2,   SPR_BAL1, 3|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_TBALLX3,   SPR_BAL1, 4|FF_FULLBRIGHT, 6, A_NULL, S_NULL

    STSEQ S_BRBALL1,   SPR_BAL7, 0|FF_FULLBRIGHT, 4, A_NULL
    STDEF S_BRBALL2,   SPR_BAL7, 1|FF_FULLBRIGHT, 4, A_NULL, S_BRBALL1
    STSEQ S_BRBALLX1,  SPR_BAL7, 2|FF_FULLBRIGHT, 6, A_NULL
    STSEQ S_BRBALLX2,  SPR_BAL7, 3|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_BRBALLX3,  SPR_BAL7, 4|FF_FULLBRIGHT, 6, A_NULL, S_NULL

    STDEF S_ROCKET,    SPR_MISL, 0|FF_FULLBRIGHT, 1, A_NULL, S_ROCKET
    STSEQ S_EXPLODE1,  SPR_BEXP, 0|FF_FULLBRIGHT, 8, A_Explode
    STSEQ S_EXPLODE2,  SPR_BEXP, 1|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_EXPLODE3,  SPR_BEXP, 2|FF_FULLBRIGHT, 4, A_NULL, S_NULL

    STSEQ S_PLASBALL,  SPR_PLSS, 0|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_PLASBALL2, SPR_PLSS, 1|FF_FULLBRIGHT, 6, A_NULL, S_PLASBALL
    STSEQ S_PLASEXP,   SPR_PLSS, 2|FF_FULLBRIGHT, 4, A_NULL
    STSEQ S_PLASEXP2,  SPR_PLSS, 3|FF_FULLBRIGHT, 4, A_NULL
    STDEF S_PLASEXP3,  SPR_PLSS, 4|FF_FULLBRIGHT, 4, A_NULL, S_NULL

    STSEQ S_BFGSHOT,   SPR_BFS1, 0|FF_FULLBRIGHT, 4, A_NULL
    STDEF S_BFGSHOT2,  SPR_BFS1, 1|FF_FULLBRIGHT, 4, A_NULL, S_BFGSHOT
    STSEQ S_BFGLAND,   SPR_BFS1, 2|FF_FULLBRIGHT, 8, A_BFGSpray
    STSEQ S_BFGLAND2,  SPR_BFS1, 3|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_BFGLAND3,  SPR_BFS1, 4|FF_FULLBRIGHT, 6, A_NULL, S_NULL

; ------------------------------ эффекты ------------------------------------
    STSEQ S_PUFF1,     SPR_PUFF, 0|FF_FULLBRIGHT, 4, A_NULL
    STSEQ S_PUFF2,     SPR_PUFF, 1, 4, A_NULL
    STSEQ S_PUFF3,     SPR_PUFF, 2, 4, A_NULL
    STDEF S_PUFF4,     SPR_PUFF, 3, 4, A_NULL, S_NULL

    STSEQ S_BLOOD1,    SPR_BLUD, 2, 8, A_NULL
    STSEQ S_BLOOD2,    SPR_BLUD, 1, 8, A_NULL
    STDEF S_BLOOD3,    SPR_BLUD, 0, 8, A_NULL, S_NULL

    STSEQ S_TFOG1,     SPR_TFOG, 0|FF_FULLBRIGHT, 6, A_NULL
    STSEQ S_TFOG2,     SPR_TFOG, 1|FF_FULLBRIGHT, 6, A_NULL
    STSEQ S_TFOG3,     SPR_TFOG, 2|FF_FULLBRIGHT, 6, A_NULL
    STDEF S_TFOG4,     SPR_TFOG, 3|FF_FULLBRIGHT, 6, A_NULL, S_NULL

; ------------------------------ бочка --------------------------------------
    STSEQ S_BAR1,      SPR_BAR1, 0, 6, A_NULL
    STDEF S_BAR2,      SPR_BAR1, 1, 6, A_NULL, S_BAR1
    STSEQ S_BEXP1,     SPR_BEXP, 0|FF_FULLBRIGHT, 5, A_NULL
    STSEQ S_BEXP2,     SPR_BEXP, 1|FF_FULLBRIGHT, 5, A_Scream
    STSEQ S_BEXP3,     SPR_BEXP, 2|FF_FULLBRIGHT, 5, A_NULL
    STSEQ S_BEXP4,     SPR_BEXP, 2|FF_FULLBRIGHT,10, A_Explode
    STDEF S_BEXP5,     SPR_BEXP, 2|FF_FULLBRIGHT,10, A_NULL, S_NULL

; ------------------------------ колонна ------------------------------------
    STDEF S_COLU,      SPR_COLU, 0|FF_FULLBRIGHT, -1, A_NULL, S_COLU

; ------------------------------ предметы -----------------------------------
%macro ITEMSTATE 3          ; имя, спрайт, кадр
    STDEF %1, %2, %3, -1, A_NULL, %1
%endmacro
%macro ITEMBLINK 2          ; имя, спрайт -- мигающий предмет (4 кадра)
    STSEQ %1,       %2, 0|FF_FULLBRIGHT, 6, A_NULL
    STSEQ %{1}B,    %2, 1|FF_FULLBRIGHT, 6, A_NULL
    STSEQ %{1}C,    %2, 2|FF_FULLBRIGHT, 6, A_NULL
    STDEF %{1}D,    %2, 3|FF_FULLBRIGHT, 6, A_NULL, %1
%endmacro

    ITEMBLINK S_BON1, SPR_BON1
    ITEMBLINK S_BON2, SPR_BON2
    ITEMBLINK S_SOUL, SPR_SOUL
    ITEMBLINK S_PINV, SPR_PINV
    ITEMBLINK S_PSTR, SPR_PSTR
    ITEMBLINK S_PINS, SPR_PINS
    ITEMBLINK S_BKEY, SPR_BKEY
    ITEMBLINK S_YKEY, SPR_YKEY
    ITEMBLINK S_RKEY, SPR_RKEY

    ITEMSTATE S_STIM, SPR_STIM, 0
    ITEMSTATE S_MEDI, SPR_MEDI, 0
    ITEMSTATE S_ARM1, SPR_ARM1, 0
    ITEMSTATE S_ARM2, SPR_ARM2, 0
    ITEMSTATE S_CLIP, SPR_CLIP, 0
    ITEMSTATE S_AMMO, SPR_AMMO, 0
    ITEMSTATE S_SHEL, SPR_SHEL, 0
    ITEMSTATE S_SBOX, SPR_SBOX, 0
    ITEMSTATE S_ROCK, SPR_ROCK, 0
    ITEMSTATE S_BROK, SPR_BROK, 0
    ITEMSTATE S_CELL, SPR_CELL, 0
    ITEMSTATE S_CELP, SPR_CELP, 0
    ITEMSTATE S_BPAK, SPR_BPAK, 0
    ITEMSTATE S_SHOTG,SPR_SHOT, 0
    ITEMSTATE S_MGUN, SPR_MGUN, 0
    ITEMSTATE S_LAUN, SPR_LAUN, 0
    ITEMSTATE S_PLASW,SPR_PLAS, 0
    ITEMSTATE S_BFUG, SPR_BFUG, 0
    ITEMSTATE S_CSAW, SPR_CSAW, 0
    ITEMSTATE S_SUIT, SPR_SUIT, 0
    ITEMSTATE S_PMAP, SPR_PMAP, 0
    ITEMSTATE S_PVIS, SPR_PVIS, 0

; ------------------------------ оружие в руках -----------------------------
    STDEF S_LIGHTDONE, SPR_FLSH, 0, 0, A_Light0, S_NULL
    STDEF S_PUNCH,     SPR_PUNG, 0, 1, A_WeaponReady, S_PUNCH
    STDEF S_PUNCHDOWN, SPR_PUNG, 0, 1, A_Lower, S_PUNCHDOWN
    STDEF S_PUNCHUP,   SPR_PUNG, 0, 1, A_Raise, S_PUNCHUP
    STSEQ S_PUNCH1,    SPR_PUNG, 1, 4, A_NULL
    STSEQ S_PUNCH2,    SPR_PUNG, 2, 4, A_Punch
    STSEQ S_PUNCH3,    SPR_PUNG, 3, 5, A_NULL
    STSEQ S_PUNCH4,    SPR_PUNG, 2, 4, A_NULL
    STDEF S_PUNCH5,    SPR_PUNG, 1, 5, A_ReFire, S_PUNCH

    STDEF S_PISTOL,    SPR_PISG, 0, 1, A_WeaponReady, S_PISTOL
    STDEF S_PISTOLDOWN,SPR_PISG, 0, 1, A_Lower, S_PISTOLDOWN
    STDEF S_PISTOLUP,  SPR_PISG, 0, 1, A_Raise, S_PISTOLUP
    STSEQ S_PISTOL1,   SPR_PISG, 0, 4, A_NULL
    STSEQ S_PISTOL2,   SPR_PISG, 1, 6, A_FirePistol
    STSEQ S_PISTOL3,   SPR_PISG, 2, 4, A_NULL
    STDEF S_PISTOL4,   SPR_PISG, 1, 5, A_ReFire, S_PISTOL
    STDEF S_PISTOLFLASH,SPR_FLSH,0|FF_FULLBRIGHT, 7, A_Light1, S_LIGHTDONE

    STDEF S_SGUN,      SPR_SHTG, 0, 1, A_WeaponReady, S_SGUN
    STDEF S_SGUNDOWN,  SPR_SHTG, 0, 1, A_Lower, S_SGUNDOWN
    STDEF S_SGUNUP,    SPR_SHTG, 0, 1, A_Raise, S_SGUNUP
    STSEQ S_SGUN1,     SPR_SHTG, 0, 3, A_NULL
    STSEQ S_SGUN2,     SPR_SHTG, 0, 7, A_FireShotgun
    STSEQ S_SGUN3,     SPR_SHTG, 1, 5, A_NULL
    STSEQ S_SGUN4,     SPR_SHTG, 2, 5, A_NULL
    STSEQ S_SGUN5,     SPR_SHTG, 3, 4, A_NULL
    STSEQ S_SGUN6,     SPR_SHTG, 2, 5, A_NULL
    STSEQ S_SGUN7,     SPR_SHTG, 1, 5, A_NULL
    STSEQ S_SGUN8,     SPR_SHTG, 0, 3, A_NULL
    STDEF S_SGUN9,     SPR_SHTG, 0, 7, A_ReFire, S_SGUN
    STDEF S_SGUNFLASH, SPR_FLSH, 1|FF_FULLBRIGHT, 7, A_Light1, S_LIGHTDONE

    STDEF S_CHAIN,     SPR_CHGG, 0, 1, A_WeaponReady, S_CHAIN
    STDEF S_CHAINDOWN, SPR_CHGG, 0, 1, A_Lower, S_CHAINDOWN
    STDEF S_CHAINUP,   SPR_CHGG, 0, 1, A_Raise, S_CHAINUP
    STSEQ S_CHAIN1,    SPR_CHGG, 0, 4, A_FireCGun
    STSEQ S_CHAIN2,    SPR_CHGG, 1, 4, A_FireCGun
    STDEF S_CHAIN3,    SPR_CHGG, 1, 0, A_ReFire, S_CHAIN
    STDEF S_CHAINFLASH,SPR_FLSH, 0|FF_FULLBRIGHT, 5, A_Light1, S_LIGHTDONE

    STDEF S_MISSILE,   SPR_MISG, 0, 1, A_WeaponReady, S_MISSILE
    STDEF S_MISSILEDOWN,SPR_MISG,0, 1, A_Lower, S_MISSILEDOWN
    STDEF S_MISSILEUP, SPR_MISG, 0, 1, A_Raise, S_MISSILEUP
    STSEQ S_MISSILE1,  SPR_MISG, 1, 8, A_GunFlash
    STSEQ S_MISSILE2,  SPR_MISG, 1,12, A_FireMissile
    STDEF S_MISSILE3,  SPR_MISG, 1, 0, A_ReFire, S_MISSILE
    STDEF S_MISSILEFLASH,SPR_FLSH,1|FF_FULLBRIGHT, 4, A_Light1, S_LIGHTDONE

    STDEF S_PLASMA,    SPR_PLSG, 0, 1, A_WeaponReady, S_PLASMA
    STDEF S_PLASMADOWN,SPR_PLSG, 0, 1, A_Lower, S_PLASMADOWN
    STDEF S_PLASMAUP,  SPR_PLSG, 0, 1, A_Raise, S_PLASMAUP
    STSEQ S_PLASMA1,   SPR_PLSG, 0, 3, A_FirePlasma
    STDEF S_PLASMA2,   SPR_PLSG, 1,20, A_ReFire, S_PLASMA
    STDEF S_PLASMAFLASH,SPR_FLSH,0|FF_FULLBRIGHT, 4, A_Light1, S_LIGHTDONE

    STDEF S_BFG,       SPR_BFGG, 0, 1, A_WeaponReady, S_BFG
    STDEF S_BFGDOWN,   SPR_BFGG, 0, 1, A_Lower, S_BFGDOWN
    STDEF S_BFGUP,     SPR_BFGG, 0, 1, A_Raise, S_BFGUP
    STSEQ S_BFG1,      SPR_BFGG, 0,20, A_NULL
    STSEQ S_BFG2,      SPR_BFGG, 1,10, A_GunFlash
    STSEQ S_BFG3,      SPR_BFGG, 1,10, A_FireBFG
    STDEF S_BFG4,      SPR_BFGG, 1,20, A_ReFire, S_BFG
    STDEF S_BFGFLASH,  SPR_FLSH, 1|FF_FULLBRIGHT, 11, A_Light2, S_LIGHTDONE

    STDEF S_SAW,       SPR_SAWG, 0, 4, A_WeaponReady, S_SAW
    STDEF S_SAWDOWN,   SPR_SAWG, 0, 1, A_Lower, S_SAWDOWN
    STDEF S_SAWUP,     SPR_SAWG, 0, 1, A_Raise, S_SAWUP
    STSEQ S_SAW1,      SPR_SAWG, 0, 4, A_Saw
    STSEQ S_SAW2,      SPR_SAWG, 1, 4, A_Saw
    STDEF S_SAW3,      SPR_SAWG, 1, 0, A_ReFire, S_SAW

NUMSTATES equ NST

; ===========================================================================
;  mobjinfo
; ===========================================================================
%macro MI 23
    dd %1, %2, %3, %4, %5, %6, %7, %8, %9, %{10}, %{11}, %{12}
    dd %{13}, %{14}, %{15}, %{16}, %{17}, %{18}, %{19}, %{20}, %{21}, %{22}
    dd %{23}, 0
%endmacro

%assign NMT 0
%macro MTDEF 1
    %assign %1 NMT
    %assign NMT NMT+1
%endmacro

MTDEF MT_PLAYER
MTDEF MT_POSSESSED
MTDEF MT_SHOTGUY
MTDEF MT_TROOP
MTDEF MT_SERGEANT
MTDEF MT_SHADOWS
MTDEF MT_HEAD
MTDEF MT_BRUISER
MTDEF MT_SKULL
MTDEF MT_BARREL
MTDEF MT_TROOPSHOT
MTDEF MT_BRUISERSHOT
MTDEF MT_ROCKET
MTDEF MT_PLASMA
MTDEF MT_BFG
MTDEF MT_PUFF
MTDEF MT_BLOOD
MTDEF MT_TFOG
MTDEF MT_TELEPORTMAN
MTDEF MT_MISC_COLUMN
MTDEF MT_MISC_BON1
MTDEF MT_MISC_BON2
MTDEF MT_MISC_SOUL
MTDEF MT_MISC_INV
MTDEF MT_MISC_STR
MTDEF MT_MISC_INS
MTDEF MT_MISC_SUIT
MTDEF MT_MISC_PMAP
MTDEF MT_MISC_PVIS
MTDEF MT_MISC_STIM
MTDEF MT_MISC_MEDI
MTDEF MT_MISC_ARM1
MTDEF MT_MISC_ARM2
MTDEF MT_MISC_BKEY
MTDEF MT_MISC_YKEY
MTDEF MT_MISC_RKEY
MTDEF MT_MISC_CLIP
MTDEF MT_MISC_AMMO
MTDEF MT_MISC_SHEL
MTDEF MT_MISC_SBOX
MTDEF MT_MISC_ROCK
MTDEF MT_MISC_BROK
MTDEF MT_MISC_CELL
MTDEF MT_MISC_CELP
MTDEF MT_MISC_BPAK
MTDEF MT_MISC_SHOTGUN
MTDEF MT_MISC_CHAINGUN
MTDEF MT_MISC_LAUNCHER
MTDEF MT_MISC_PLASMA
MTDEF MT_MISC_BFG
MTDEF MT_MISC_CHAINSAW
NUMMOBJTYPES equ NMT

    align 8
mobjinfo:
;  doomed spawn  hp   see        seesnd react atksnd pain      chance psnd  melee      missile     death       xdeath  dsnd  speed radius height mass dmg actsnd flags raise
 MI -1, S_PLAY,  100, S_PLAY_RUN1, 0,   0,    0,     S_PLAY_PAIN,255,0,    S_NULL,    S_PLAY_ATK1,S_PLAY_DIE1,S_NULL, 0,    0,    16*FRACUNIT,56*FRACUNIT,100,0,0, MF_SOLID|MF_SHOOTABLE|MF_DROPOFF|MF_PICKUP|MF_NOTDMATCH, S_NULL
 MI 3004,S_POSS_STND,20,S_POSS_RUN1,sfx_posit,8,sfx_pistol,S_POSS_PAIN,200,sfx_popain,S_NULL,S_POSS_ATK1,S_POSS_DIE1,S_NULL,sfx_podth,8,20*FRACUNIT,56*FRACUNIT,100,0,sfx_posact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL, S_NULL
 MI 9,   S_SPOS_STND,30,S_SPOS_RUN1,sfx_posit,8,sfx_shotgn,S_SPOS_PAIN,170,sfx_popain,S_NULL,S_SPOS_ATK1,S_SPOS_DIE1,S_NULL,sfx_podth,8,20*FRACUNIT,56*FRACUNIT,100,0,sfx_posact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL, S_NULL
 MI 3001,S_TROO_STND,60,S_TROO_RUN1,sfx_bgsit,8,sfx_bgatk,S_TROO_PAIN,200,sfx_popain,S_TROO_ATK1,S_TROO_ATK1,S_TROO_DIE1,S_NULL,sfx_bgdth,8,20*FRACUNIT,56*FRACUNIT,100,0,sfx_bgact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL, S_NULL
 MI 3002,S_SARG_STND,150,S_SARG_RUN1,sfx_sgtsit,8,sfx_sgtatk,S_SARG_PAIN,180,sfx_dmpain,S_SARG_ATK1,S_NULL,S_SARG_DIE1,S_NULL,sfx_sgtdth,10,30*FRACUNIT,56*FRACUNIT,400,0,sfx_dmact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL, S_NULL
 MI 58,  S_SARG_STND,150,S_SARG_RUN1,sfx_sgtsit,8,sfx_sgtatk,S_SARG_PAIN,180,sfx_dmpain,S_SARG_ATK1,S_NULL,S_SARG_DIE1,S_NULL,sfx_sgtdth,10,30*FRACUNIT,56*FRACUNIT,400,0,sfx_dmact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL|MF_SHADOW, S_NULL
 MI 3005,S_HEAD_STND,400,S_HEAD_RUN1,sfx_cacsit,8,0,S_HEAD_PAIN,128,sfx_dmpain,S_NULL,S_HEAD_ATK1,S_HEAD_DIE1,S_NULL,sfx_cacdth,8,31*FRACUNIT,56*FRACUNIT,400,0,sfx_dmact,MF_SOLID|MF_SHOOTABLE|MF_FLOAT|MF_NOGRAVITY|MF_COUNTKILL, S_NULL
 MI 3003,S_BOSS_STND,1000,S_BOSS_RUN1,sfx_brssit,8,0,S_BOSS_PAIN,50,sfx_dmpain,S_BOSS_ATK1,S_BOSS_ATK1,S_BOSS_DIE1,S_NULL,sfx_brsdth,8,24*FRACUNIT,64*FRACUNIT,1000,0,sfx_dmact,MF_SOLID|MF_SHOOTABLE|MF_COUNTKILL, S_NULL
 MI 3006,S_SKULL_STND,100,S_SKULL_RUN1,0,8,sfx_sklatk,S_SKULL_PAIN,256,sfx_dmpain,S_NULL,S_SKULL_ATK1,S_SKULL_DIE1,S_NULL,sfx_firxpl,8,16*FRACUNIT,56*FRACUNIT,50,3,sfx_dmact,MF_SOLID|MF_SHOOTABLE|MF_FLOAT|MF_NOGRAVITY, S_NULL
 MI 2035,S_BAR1,   20, S_NULL,   0,0,0, S_NULL,0,0, S_NULL,S_NULL, S_BEXP1, S_NULL,0, 0, 10*FRACUNIT,42*FRACUNIT,100,0,0, MF_SOLID|MF_SHOOTABLE|MF_NOBLOOD, S_NULL
 MI -1,  S_TBALL1, 1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_TBALLX1,S_NULL,sfx_firxpl,10*FRACUNIT,6*FRACUNIT,8*FRACUNIT,100,3,0, MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY, S_NULL
 MI -1,  S_BRBALL1,1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_BRBALLX1,S_NULL,sfx_firxpl,15*FRACUNIT,6*FRACUNIT,8*FRACUNIT,100,8,0, MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY, S_NULL
 MI -1,  S_ROCKET, 1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_EXPLODE1,S_NULL,sfx_barexp,20*FRACUNIT,11*FRACUNIT,8*FRACUNIT,100,20,0, MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY, S_NULL
 MI -1,  S_PLASBALL,1000,S_NULL, 0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_PLASEXP,S_NULL,sfx_firxpl,25*FRACUNIT,13*FRACUNIT,8*FRACUNIT,100,5,0, MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY, S_NULL
 MI -1,  S_BFGSHOT,1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_BFGLAND,S_NULL,sfx_rxplod,25*FRACUNIT,13*FRACUNIT,8*FRACUNIT,100,100,0, MF_NOBLOCKMAP|MF_MISSILE|MF_DROPOFF|MF_NOGRAVITY, S_NULL
 MI -1,  S_PUFF1,  1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_NOBLOCKMAP|MF_NOGRAVITY, S_NULL
 MI -1,  S_BLOOD1, 1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_NOBLOCKMAP, S_NULL
 MI -1,  S_TFOG1,  1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_NOBLOCKMAP|MF_NOGRAVITY, S_NULL
 MI 14,  S_NULL,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_NOBLOCKMAP|MF_NOSECTOR, S_NULL
 MI 2028,S_COLU,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 16*FRACUNIT,48*FRACUNIT,100,0,0, MF_SOLID, S_NULL
 MI 2014,S_BON1,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2015,S_BON2,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2013,S_SOUL,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2022,S_PINV,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2023,S_PSTR,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2024,S_PINS,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2025,S_SUIT,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2026,S_PMAP,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2045,S_PVIS,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_COUNTITEM, S_NULL
 MI 2011,S_STIM,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2012,S_MEDI,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2018,S_ARM1,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2019,S_ARM2,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 5,   S_BKEY,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_NOTDMATCH, S_NULL
 MI 6,   S_YKEY,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_NOTDMATCH, S_NULL
 MI 13,  S_RKEY,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL|MF_NOTDMATCH, S_NULL
 MI 2007,S_CLIP,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2048,S_AMMO,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2008,S_SHEL,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2049,S_SBOX,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2010,S_ROCK,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2046,S_BROK,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2047,S_CELL,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 17,  S_CELP,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 8,   S_BPAK,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2001,S_SHOTG,  1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2002,S_MGUN,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2003,S_LAUN,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2004,S_PLASW,  1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2006,S_BFUG,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
 MI 2005,S_CSAW,   1000,S_NULL,  0,8,0, S_NULL,0,0, S_NULL,S_NULL, S_NULL,S_NULL,0, 0, 20*FRACUNIT,16*FRACUNIT,100,0,0, MF_SPECIAL, S_NULL
